import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-water-utility-nonrevenue-water-recovery",
  "engine": "recovery",
  "title": "Water Utility Non-Revenue Water Recovery",
  "shortTitle": "Water Utility Non-Revenue Water Recovery",
  "tagline": "Quantify apparent and real water losses, prioritize recoverable billing leakage, and measure repair economics.",
  "industry": "Water Utility Revenue Assurance",
  "buyer": "Municipal and investor-owned water utilities",
  "uiPort": 4717,
  "apiPort": 5717,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Water Utility Non-Revenue Water Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections in one accountable workflow. Quantify apparent and real water losses, prioritize recoverable billing leakage, and measure repair economics.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Water Utility Non-Revenue Water Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("water-balance-registry","WUN01","Water balance registry","Execute water balance registry using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed water balance registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Water balance registry Reference","text","WUN01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("production-meter-ingestion","WUN02","Production meter ingestion","Execute production meter ingestion using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed production meter ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Production meter ingestion Reference","text","WUN02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("district-meter-ingestion","WUN03","District meter ingestion","Execute district meter ingestion using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed district meter ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","District meter ingestion Reference","text","WUN03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("customer-consumption-ingestion","WUN04","Customer consumption ingestion","Execute customer consumption ingestion using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed customer consumption ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Customer consumption ingestion Reference","text","WUN04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("authorized-unbilled-use","WUN05","Authorized unbilled use","Execute authorized unbilled use using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed authorized unbilled use decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Authorized unbilled use Reference","text","WUN05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("meter-under-registration","WUN06","Meter under-registration","Execute meter under-registration using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed meter under-registration decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Meter under-registration Reference","text","WUN06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("data-handling-error-detection","WUN07","Data handling error detection","Execute data handling error detection using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed data handling error detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Data handling error detection Reference","text","WUN07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("unauthorized-consumption","WUN08","Unauthorized consumption","Execute unauthorized consumption using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed unauthorized consumption decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Unauthorized consumption Reference","text","WUN08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("real-loss-calculation","WUN09","Real loss calculation","Execute real loss calculation using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed real loss calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Real loss calculation Reference","text","WUN09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("leak-event-prioritization","WUN10","Leak event prioritization","Execute leak event prioritization using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed leak event prioritization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Leak event prioritization Reference","text","WUN10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("pressure-management-analysis","WUN11","Pressure management analysis","Execute pressure management analysis using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed pressure management analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Pressure management analysis Reference","text","WUN11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("meter-replacement-economics","WUN12","Meter replacement economics","Execute meter replacement economics using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed meter replacement economics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Meter replacement economics Reference","text","WUN12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("billing-correction-workflow","WUN13","Billing correction workflow","Execute billing correction workflow using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed billing correction workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Billing correction workflow Reference","text","WUN13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("recovered-revenue-tracking","WUN14","Recovered revenue tracking","Execute recovered revenue tracking using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed recovered revenue tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","Recovered revenue tracking Reference","text","WUN14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]}),
feature("district-loss-analytics","WUN15","District loss analytics","Execute district loss analytics using production meters, district meters, customer meters, billing, pressure, leak events, authorized unbilled use, meter accuracy, repairs, and collections.","Produce a governed district loss analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / District Meter Area","text","Utility / District Meter Area · Standard Case"],["caseReference","District loss analytics Reference","text","WUN15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1525000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1845250],["domainDriver","Loss Type","select","Apparent loss",["Apparent loss","Real loss","Authorized unbilled"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Water balance registry case","Production meter ingestion case","District meter ingestion case","Customer consumption ingestion case","Authorized unbilled use case"]})
]);
